### ISSUE TITLE
Could not synchronise configuration

### ISSUE THREAD

**Issue by opi** [backdrop-contrib/splashify#8]
## Describe your issue

Configuration changes could not be imported from an environment to another, because the configuration file is not declared.
![capture d ecran de 2018-10-02 12-10-46](https://user-images.githubusercontent.com/159548/46342916-61720580-c63c-11e8-8dee-3704d4731a7a.png)

### Steps to reproduce (if reporting a bug)

1. Do any change to the `splashify.settings.json` configuration file
2. Visit `admin/config/development/configuration` and try to import the new configuration

### Actual behavior (if reporting a bug)

Following error, and config is not imported
> The configuration "splashify.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

### Expected behavior (if reporting a bug)

Configuration changes should be imported without any error

### Fix

Implements the `hook_config_info` hook to declare this custom configuration file.

I will open a PR right after creating this issue !

**Comment by opi** [comment]
There you go https://github.com/backdrop-contrib/splashify/pull/9

**Comment by laryn** [comment]
Thanks @opi !
